In [ ]:
import pandas as pd
import numpy as np

import re
import string

import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
resume_df = pd.read_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/resume_clean.csv"
)

jobs_df = pd.read_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/jobs_clean.csv"
)

extra_jobs_df = pd.read_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/extra_jobs_clean.csv"
)

In [ ]:
print(resume_df.shape)

print(jobs_df.shape)

print(extra_jobs_df.shape)

(2481, 2)
(5000, 6)
(12856, 2)

In [ ]:
stop_words = set(stopwords.words('english'))

lemmatizer = WordNetLemmatizer()

In [ ]:
def clean_text(text):

    # Convert to string
    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # Remove email addresses
    text = re.sub(r'\S+@\S+', ' ', text)

    # Remove phone numbers
    text = re.sub(r'\+?\d[\d\s\-\(\)]{8,}\d', ' ', text)

    # Remove numbers
    text = re.sub(r'\d+', ' ', text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # Tokenization
    words = word_tokenize(text)

    # Stopword Removal + Lemmatization
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

In [ ]:
resume_df["Clean_Resume"] = resume_df["Resume_str"].apply(clean_text)

In [ ]:
resume_df[["Resume_str", "Clean_Resume"]].head()

,Resume_str,Clean_Resume
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,hr administratormarketing associate hr adminis...
1,"HR SPECIALIST, US HR OPERATIONS ...",hr specialist u hr operation summary versatile...
2,HR DIRECTOR Summary Over 2...,hr director summary year experience recruiting...
3,HR SPECIALIST Summary Dedica...,hr specialist summary dedicated driven dynamic...
4,HR MANAGER Skill Highlights ...,hr manager skill highlight hr skill hr departm...

In [ ]:
jobs_df["Clean_Skills"] = jobs_df["Skills_Required"].apply(clean_text)

In [ ]:
jobs_df[["Skills_Required", "Clean_Skills"]].head()

,Skills_Required,Clean_Skills
0,"Kotlin, Java, REST APIs",kotlin java rest apis
1,"Selenium, Manual Testing, Postman, API Testing...",selenium manual testing postman api testing py...
2,"JIRA, Excel, Power BI",jira excel power bi
3,"Penetration Testing, Python, Ethical Hacking, ...",penetration testing python ethical hacking sie...
4,"Docker, REST APIs, AWS, PostgreSQL",docker rest apis aws postgresql

In [ ]:
extra_jobs_df["Clean_Description"] = extra_jobs_df["description"].apply(clean_text)

In [ ]:
extra_jobs_df[["description", "Clean_Description"]].head()

,description,Clean_Description
0,Diagnose computer errors and triage to determi...,diagnose computer error triage determine urgen...
1,Job Responsibilities:. . As a Clinical Res...,job responsibility clinical research associate...
2,Role: ETL Data Engineer with Oracle Data ...,role etl data engineer oracle data integrator ...
3,Assumes primary responsibility of unit secreta...,assumes primary responsibility unit secretaria...
4,Back to job search Data Analyst - Intex Dev...,back job search data analyst intex developer n...

In [ ]:
resume_df.to_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/resume_preprocessed.csv",
    index=False
)

jobs_df.to_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/jobs_preprocessed.csv",
    index=False
)

extra_jobs_df.to_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/extra_jobs_preprocessed.csv",
    index=False
)

print("✅ Preprocessed datasets saved successfully!")

✅ Preprocessed datasets saved successfully!