In [1]:
import pandas as pd
import numpy as np

import re

from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
resume_df = pd.read_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/resume_preprocessed.csv"
)

extra_jobs_df = pd.read_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/extra_jobs_preprocessed.csv"
)

In [5]:
resume_df.columns

Index(['Resume_str', 'Category', 'Clean_Resume'], dtype='object')

In [6]:
extra_jobs_df.columns

Index(['title', 'description', 'Clean_Description'], dtype='object')

In [7]:
skill_keywords = {

    "Python",
    "Java",
    "C++",
    "C",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "MongoDB",

    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "Keras",

    "NLP",
    "Computer Vision",

    "Docker",
    "Kubernetes",

    "AWS",
    "Azure",
    "GCP",

    "Linux",
    "Git",
    "GitHub",

    "JavaScript",
    "React",
    "Node.js",

    "HTML",
    "CSS",

    "Power BI",
    "Tableau",

    "Pandas",
    "NumPy",
    "Scikit-learn",

    "Spark",
    "Hadoop",

    "DevOps",

    "Cybersecurity",

    "Networking",

    "Data Analysis",

    "Excel",

    "REST API"

}

In [8]:
def extract_skills(text):

    text = str(text).lower()

    found_skills = []

    for skill in skill_keywords:

        if skill.lower() in text:

            found_skills.append(skill)

    return sorted(list(set(found_skills)))

In [12]:
sample_resume = resume_df.loc[1800, "Clean_Resume"]
print(sample_resume)

qa engineering team lead career overview eight year progressive technical experience quality assurance engineering computer software window environment strong practical theoretical knowledge software quality assurance tool technique proven ability develop system test strategy methodology fullscale system integration testing quality reliability functionality computability expertise development ieee compliant testing documentation key contributor software development team supporting release many new product release several major upgrade existing product experience testing large complex clientserver database application multiplatform product delivery experience pc system experienced window graphical product networking andor data acquisition software experienced manual automated testing working project diverse scope able expertise judgment within defined parameter strong knowledge automated manual black box testing including acceptance functional regression stress compatibility integration testing technique bug reporting error handling responsibility include review software requirement functional specification document participation code walktrough assist design development test plan procedure secure position allow exercise skill obtained education prior work experience qualification analytical problem solving stress tolerance communication skill leadership skill ability resolve nonroutine complex business issue anticipate problem develop alternate solution manage execution successfully ability maintain high energy level extended period time ability communicate clearly efficiently verbally writing ability develop maintain close working relationship end user business analyst documentation specialist tester developer senior management experience building leading closeknit team demanding environment ambiguous undefined frequently changing requirement work experience company name march july qa engineering team lead city state imagicasttm first endtoend service give today educated consumer exactly want retail floor rich product information personalization access unlimited inventory internet combined immediate gratification instore purchase primary responsibility quality imagicast product line lead qa team assigned imagicast related quality task established appropriate qa method inspection test documentation verify software quality prior release shipping product also involved diagnosis product failure performance problem reported field qa task applicable product included verifying operation dvd playback system verifying operation peripheral device eg keyboard printer connected embedded system verifying data collection function wireless data network verifying presentation html page internet device performed qa test complex multi threaded system interpreting specification product feature designed appropriate test case applied qa process reveal functional performance problem affecting web page real time embedded system responsibility included verifying data warehousing data mining application used business intelligence ebusiness server side application multichannel business application personalization feature virtual inventory management application typically found click mortar business company name may february quality assurance engineering manager city state senticaxchangetm mobile solution quickly enables alert twoway push pull transaction content delivery wireless device well landline phone sentica xchangetm approach enables user application initiate communication session complete transaction time interact transact onthego subscriber receive immediate confirmation response telephone cell phone wireless application protocol wap device pda palm vii ce device pocket pc pager well build single implementation desired application enable text voice image video data communication device senticaxchangetm system administration management module functionality provides full access customer information touchpoint enterprise customer employee interact customer application provide breadth functionality needed succeed competitive wireless business primarily responsible performing analysis existing job flow coordination update system documentation providing proposal change needed assisting test execution performed analysis test document design different project within senticaxchangetm including adt gui tool application development tool composer api sam system administration management interface utilizing unix oraclesql various network protocol company name november may qa lead customer careservice application city state oracle customer careservice application full business process management provided functionality support scheduling dispatching spare part logistics service billing field service well contract rounding offering customer care functionality provides full access customer information touchpoint enterprise customer care agent employee interact customer application provide breadth functionality needed succeed competitive support field service depot repair business full business process management provided functionality support scheduling dispatching spare part logistics service billing mobile field service well contract rounding offering customer care functionality provides full access customer information touchpoint enterprise customer care agent employee interact customer performed analysis test document designfor oracle customer careservice application including oracle telephony management otm system otm highvolume crossplatform interface engine utilizing unix xc oraclesql various network protocol primarily responsible performing analysis existing job flow coordination update system documentation providing proposal change needed assisting test execution oracle maintenance repair overhaul mro system resource planning module srp performed high mediumlevel analysis maintenance repair overhaul mro system resource planning srp module within oracle application system decentralized running various platform primarily responsible oversight qa testing process deliverable provided detailed recommendation including complete time cost estimation test process including direction management oversight activity involved defining related requirement infrastructure standard training support method procedure also heavily involved strategic planning related corporatewide year certification coordinated enduser system support staff training administered issue management required escalation jeopardy notification resolution provided verbal written status report seniorlevel management regular basis worked closely civil software engineer create easy use understand informational product nt environment provided change risk implementation management held ultimate responsibility deliverable status report final product delivery designed developed qa test plan manual automated test script quality assurance windowsbased application functionality responsibility included coordination application support activity application analysis testing well operating system support maintenance also assisted coordination delivery enduser training company name february november mail software quality engineer ii city state quality assurance manager role responsibility included leading qa team black box white box testing distributed architecture system client server component proactively involved code walk trough design review meeting learn product great understanding software developed able execute testing lowlevel communication protocol backend database system lead developing test plan test case regression suite make sure test plan executed result communicated developed strategy together development qa team improving qualitytestability component usability final product company name september february senior quality assurance analyst city state foster city electronic invoice presentment new enhancement visa epay service provides member financial institution ability offer billers retail customer electronic invoice delivery capability eip system based window nt platform developed using visual basic access database back end system performs data transport via following communication channel m exchange virtual area network van lan compuserve sprintnet responsible developing lowlevel qa test plan qa reference documentation qa finding document pilot project assist development new testing method procedure improving testing efficiency recommended method automating testing using qa partner tool perform acceptance functional gui usability error handling stress regression testing using black box gray box testing technique validate data integrity security presented level data transport verify transmission completeness database compare input output using msdos batch file check file format known set template test data encryption password protection interviewed new applicant qa analyst position project trained new member team first day assigned responsibility team member wrote daily status report included summery activity performed shift project lead presented qa group department meeting qa team lead conference call every hour included report progress testing cycle made sure needed support provided qa team developing team performed manual automated testing application entered openfound drsbugs tracker bug tracking database verified drsbugs closefixed wrote executed test case acceptance boundary performance regression volume stress testing developed performed automated test case using qa partner window nt environment wrote finding document summary document qa team analysis finding suggestion andor concern found testing cycle project company name march september software quality assurance city state daytimer organizer window personal manager advanced feature work daytimer brand name paper different formatpersonal manager advanced feature work daytimer brand name paper different format test clientserver application database application developed nonprofit organization client donators employee event etc database developed m access m visual basic run window test functionality application creating modifying deleting record provide regression acceptance unit integration testing create execute case regression testing designating area testing develop automated test suite utilizing qa partner emphasized testing feature printing envelope label user preference startup screen entered bug lotus note bug tracking database verified bug education training national education center management city state u management minor national education center san francisco california kensington training program city state u testing computer software kensington training program san mateo california technion university b electrical engineering city il b electrical engineering technion university haifa israel certification national education center professional affiliation electronic invoice presentment new enhancement visa epay service provides member financial institution ability offer billers retail customer electronic invoice delivery capability eip system based window nt platform developed using visual basic access database back end system performs data transport via following communication channel m exchange virtual area network van lan compuserve sprintnet responsible developing lowlevel qa test plan qa reference documentation qa finding document pilot project assist development new testing method procedure improving testing efficiency recommended method automating testing using qa partner tool perform acceptance functional gui usability error handling stress regression testing using black box gray box testing technique validate data integrity security presented level data transport verify transmission completeness database compare input output using msdos batch file check file format known set template test data encryption password protection interviewed new applicant qa analyst position project trained new member team first day assigned responsibility team member wrote daily status report included summery activity performed shift project lead presented qa group department meeting qa team lead conference call every hour included report progress testing cycle made sure needed support provided qa team developing team performed manual automated testing application entered openfound drsbugs tracker bug tracking database verified drsbugs closefixed wrote executed test case acceptance boundary performance regression volume stress testing developed performed automated test case using qa partner window nt environment wrote finding document summary document qa team analysis finding suggestion andor concern found testing cycle project skill quality assurance testing access qa case database regression testing visual basic clientserver client integration integration testing integrator lotus note microsoft window m access m visual basic printing software quality assurance window electrical engineering documentation network protocol oracle proposal sql unix qa test test plan test case application analysis application support automated test script basis billing business process management c contract dispatching issue management logistics maintenance maintenance repair planning module process management qa testing scheduling staff training strategic planning system support telephony test script training graphical user interface gui wireless black box usability adt api application development pocket pc system administration system administration telephone voice wap retail retail marketing team lead architecture database system design review engineer quality engineer software quality engineer test plan white box white box testing black box testing data acquisition database db dbase dbase iv excellent verbal written communication skill ftp ieee internet explorer ipx java javascript linux m office netbeui netscape networking new product novell operation problem solving rdbms san software development software testing solution storage area network structured software system integration tcp tcpip virtual machine visual test vm assurance analyst automated testing back end data integrity do encryption exchange file invoice lan m exchange msdos progress security business intelligence collection data collection data mining data warehousing ebusiness embedded system html inspection inventory qa engineering real time real time embedded real time embedded system shipping wireless data

In [11]:
resume_skills = extract_skills(sample_resume)

print(resume_skills)

['C', 'Excel', 'HTML', 'Java', 'JavaScript', 'Linux', 'Networking', 'SQL']

In [13]:
extra_jobs_df["Extracted_Skills"] = extra_jobs_df[
    "Clean_Description"
].apply(extract_skills)

In [14]:
extra_jobs_df[
    [
        "title",
        "Extracted_Skills"
    ]
].head()

,title,Extracted_Skills
0,Help Desk Analyst- Tier II,[C]
1,Clinical Research Associate II,[C]
2,ETL Data Engineer with Oracle Data Integrator ...,"[C, Excel, Git, Linux, Python, SQL]"
3,OR COMM/DATA SUPPORT SPEC,"[C, Excel]"
4,Data Analyst - Intex Developer,"[C, Excel, Linux, Python]"

In [28]:
job_title_mapping = {

    # ---------- Engineering ----------
    "Software Engineer": "Machine Learning Software Engineer",
    "QA Engineer": "Machine Learning Software Engineer",
    "Technical Lead": "Lead Data Engineer",
    "Engineering Manager": "Lead Data Engineer",

    # ---------- Data ----------
    "Data Scientist": "Data Scientist",
    "Data Engineer": "Data Engineer",
    "Data Analyst": "Data Analyst",
    "Business Analyst": "Business Analyst",

    # ---------- AI ----------
    "AI Engineer": "Machine Learning Engineer",
    "Machine Learning Engineer": "Machine Learning Engineer",
    "MLOps Engineer": "Machine Learning Engineer",
    "Computer Vision Engineer": "Machine Learning Engineer",
    "NLP Engineer": "Machine Learning Engineer",

    # ---------- Cloud ----------
    "Cloud Engineer": "AWS Data Engineer",

    # ---------- Backend ----------
    "Backend Developer": "Database Engineer",
    "Node.js Developer": "Database Engineer",

    # ---------- Frontend ----------
    "Frontend Developer": "Software Engineer",
    "React Developer": "Software Engineer",

    # ---------- Mobile ----------
    "Android Developer": "Software Engineer",
    "iOS Developer": "Software Engineer",

    # ---------- DevOps ----------
    "DevOps Engineer": "AWS Data Engineer",

    # ---------- Cyber ----------
    "Cybersecurity Analyst": "Data Loss Prevention (DLP) Engineer (Symantec)",

    # ---------- BI ----------
    "Power BI Developer": "Data Reporting Analyst",

    # ---------- Database ----------
    "Java Developer": "Software Engineer",
    "Python Developer": "Software Engineer",

    # ---------- Product ----------
    "Product Manager": "Business Analyst",

    # ---------- Blockchain ----------
    "Blockchain Developer": "Software Engineer"
}

In [29]:
recommended_job = "QA Engineer"

mapped_job = job_title_mapping.get(
    recommended_job,
    recommended_job
)

print("Mapped Job:", mapped_job)

matching_job = extra_jobs_df[
    extra_jobs_df["title"].str.contains(
        recommended_job,
        case=False,
        na=False
    )
]

Mapped Job: Machine Learning Software Engineer

In [30]:
extra_jobs_df["title"].value_counts().head(50)

title
Data Scientist                                                  894
Data Analyst                                                    579
Machine Learning Engineer                                       365
Senior Data Scientist                                           226
Data Engineer                                                   199
Senior Data Engineer                                            131
Senior Data Analyst                                             131
Business Analyst                                                 80
Lead Data Scientist                                              76
Business Data Analyst                                            53
Financial Analyst                                                45
Sr. Data Scientist                                               39
Sr. Data Analyst                                                 38
Senior Financial Analyst                                         36
Data Research Analyst, gt.school (Remote) - $60,000/year USD     35
Data Scientist, gt.school (Remote) - $60,000/year USD            33
Junior Data Analyst                                              33
Junior Data Scientist                                            26
Principal Data Scientist                                         24
Data & Applied Scientist                                         21
Data Governance Analyst                                          21
Sr Data Scientist                                                21
Data Scientist I                                                 20
Lead Data Engineer                                               20
Lead Data Analyst                                                20
Data Center Engineer                                             20
Senior Business Analyst                                          19
Data Quality Analyst                                             18
Marketing Data Analyst                                           18
Data Analyst II                                                  18
Oracle Database Administrator                                    18
Data Analyst III                                                 17
Data Analyst Junior                                              17
Big Data Developer                                               17
Data Analyst I                                                   16
Real Estate Agent                                                16
Database Engineer                                                14
Manager, Data Loss Prevention (DLP) Engineer (Symantec)          14
AWS Data Engineer                                                14
Machine Learning Software Engineer                               14
Data Architect                                                   14
Sr. Financial Analyst                                            13
Data Entry Specialist                                            13
Financial Data Analyst                                           13
Data Reporting Analyst                                           13
Expression of Interest: Data Scientist                           13
Data Modeler                                                     13
Business Systems Analyst                                         13
Healthcare Data Analyst                                          13
Clinical Research Coordinator                                    13
Name: count, dtype: int64

In [31]:
matching_job.head()

,title,description,Clean_Description,Extracted_Skills
2744,Big Data/Machine Learning SQA Engineer,The Data Analytics team at Nova is looking ...,data analytics team nova looking big data mach...,"[C, Machine Learning]"
6477,Data Validation / QA Engineer,About US: LTIMindtree is a global technology ...,u ltimindtree global technology consulting dig...,"[C, Excel, Git, Python, SQL]"
9713,Data Validation / QA Engineer,About US:. LTIMindtree. is a global technolo...,u ltimindtree global technology consulting dig...,"[C, Excel, Git, Python, SQL]"
11844,Senior Analyst Software QA Engineering,Job ID: 2435592 BR Category: Information S...,job id br category information system address ...,"[C, Git, Java]"

In [32]:
required_skills = matching_job.iloc[0]["Extracted_Skills"]

print(required_skills)

['C', 'Machine Learning']

In [33]:
candidate_skills = set(resume_skills)

required_skills = set(required_skills)

matched_skills = candidate_skills.intersection(required_skills)

missing_skills = required_skills - candidate_skills

In [34]:
print("Candidate Skills")

print(sorted(candidate_skills))

print()

print("Required Skills")

print(sorted(required_skills))

print()

print("Matched Skills")

print(sorted(matched_skills))

print()

print("Missing Skills")

print(sorted(missing_skills))

Candidate Skills
['C', 'Excel', 'HTML', 'Java', 'JavaScript', 'Linux', 'Networking', 'SQL']

Required Skills
['C', 'Machine Learning']

Matched Skills
['C']

Missing Skills
['Machine Learning']

In [35]:
if len(required_skills) == 0:

    match_percentage = 0

else:

    match_percentage = (
        len(matched_skills)
        /
        len(required_skills)
    ) * 100

print("Skill Match:", round(match_percentage,2),"%")

Skill Match: 50.0 %

In [36]:
print("\nSuggested Skills to Learn\n")

for skill in sorted(missing_skills):

    print("-", skill)

Suggested Skills to Learn

- Machine Learning

In [38]:
extra_jobs_df.to_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/extra_jobs_with_skills.csv",
    index=False
)